name: Build library

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 17]
    steps:
      - uses: actions/checkout@master
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Compile typescript
        run: npm run build:ci
      - name: Lint typescript
        run: npm run lint:ci
      - name: Build Typedocs
        run: npm run docs
      - name: Deploy Typedocs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            branch: gh-pages
            folder: docs

