name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      - run: npm publish --unsafe-perm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
